<a href="https://colab.research.google.com/github/shrijitagithub/loginform/blob/main/Image_recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
(X_train, y_train), (X_test,y_test) = datasets.cifar10.load_data()

170498071/170498071 [==============================] - 2s 0us/step


In [ ]:
X_train.shape

(50000, 32, 32, 3)

In [ ]:
X_test.shape

(10000, 32, 32, 3)

In [ ]:
y_train.shape

(50000, 1)

In [ ]:
y_train[:5]

array([[6],
       [9],
       [9],
       [4],
       [1]], dtype=uint8)

y_train is a 2D array, for our classification having 1D array is sufficient. so have to convert this to now 1D array

In [ ]:
y_train = y_train.reshape(-1,)
y_train[:5]

array([6, 9, 9, 4, 1], dtype=uint8)

In [ ]:
y_test = y_test.reshape(-1,)

In [ ]:
classes = ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]

In [ ]:
#Normalizing the training data
X_train = X_train / 255.0
X_test = X_test / 255.0

In [ ]:
cnn = models.Sequential([
    layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(32, 32, 3)),
    layers.MaxPooling2D((2, 2)),
    
    layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

In [ ]:
cnn.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
cnn.fit(X_train, y_train, epochs=10)

Epoch 1/10
1563/1563 [==============================] - 73s 46ms/step - loss: 1.4634 - accuracy: 0.4749
Epoch 2/10
1563/1563 [==============================] - 70s 45ms/step - loss: 1.1075 - accuracy: 0.6124
Epoch 3/10
1563/1563 [==============================] - 71s 46ms/step - loss: 0.9850 - accuracy: 0.6573
Epoch 4/10
1563/1563 [==============================] - 70s 45ms/step - loss: 0.9008 - accuracy: 0.6854
Epoch 5/10
1563/1563 [==============================] - 69s 44ms/step - loss: 0.8394 - accuracy: 0.7085
Epoch 6/10
1563/1563 [==============================] - 71s 46ms/step - loss: 0.7842 - accuracy: 0.7263
Epoch 7/10
1563/1563 [==============================] - 70s 45ms/step - loss: 0.7371 - accuracy: 0.7441
Epoch 8/10
1563/1563 [==============================] - 70s 45ms/step - loss: 0.6948 - accuracy: 0.7563
Epoch 9/10
1563/1563 [==============================] - 71s 45ms/step - loss: 0.6585 - accuracy: 0.7690
Epoch 10/10
1563/1563 [==============================] - 70s 45m

In [ ]:
cnn.evaluate(X_test,y_test)

313/313 [==============================] - 5s 14ms/step - loss: 0.9548 - accuracy: 0.6877


[0.9547882080078125, 0.6876999735832214]

In [ ]:
y_pred = cnn.predict(X_test)
y_pred[:5]

313/313 [==============================] - 4s 14ms/step


array([[2.53307051e-03, 7.41314352e-06, 1.93802334e-04, 9.82498527e-01,
        3.60587321e-04, 1.06732585e-02, 1.13150035e-03, 1.57820352e-04,
        2.09970283e-03, 3.44280619e-04],
       [7.77714828e-04, 3.33979074e-03, 1.77923594e-05, 1.16662386e-06,
        1.03604464e-06, 1.02722826e-08, 1.12227463e-08, 3.97425843e-08,
        9.95859563e-01, 2.73167916e-06],
       [8.01408812e-02, 1.45265236e-01, 5.87030360e-03, 2.54998021e-02,
        4.37722728e-03, 6.84591755e-03, 9.14271746e-04, 9.59767774e-03,
        7.09883928e-01, 1.16046835e-02],
       [9.49983776e-01, 6.64565247e-04, 1.08282184e-02, 2.44286563e-03,
        1.27955945e-02, 6.88463558e-07, 1.95348844e-06, 8.85466943e-05,
        2.31900066e-02, 3.97547092e-06],
       [3.41744311e-07, 2.80210297e-05, 5.56945540e-02, 7.33301193e-02,
        2.17926547e-01, 4.63265516e-02, 6.06685162e-01, 3.89450133e-06,
        4.48915716e-06, 2.23478978e-07]], dtype=float32)

In [ ]:
y_classes = [np.argmax(element) for element in y_pred]
y_classes[:5]

[3, 8, 8, 0, 6]

In [ ]:
y_test[:5]

array([3, 8, 8, 0, 6], dtype=uint8)

In [ ]:
def plot_sample(X, y, index):
    plt.figure(figsize = (480,640))
    plt.imshow(X[index])
    plt.xlabel(classes[y[index]])
   

In [ ]:
 plot_sample(X_test, y_test,8)

NameError: ignored

In [ ]:
classes[y_classes[8]]